class TextRegristy {
  static final List<String> _sentences = [
    'The fluffy unicorn juggled pickles while riding a unicycle.',
    'Yesterday, I ate a cloud for breakfast and it tasted like regret.',
    'If frogs wore hats, would they still be amphibians?',
    'A blue spoon just told me a secret about the color orange.',
    'My socks are secretly plotting a rebellion against my shoes.',
    'The catnip plant is actually a sentient being with a vendetta against squirrels.',
    'I saw a talking pineapple wearing sunglasses at the grocery store.',
    "If the moon were made of cheese, I'd be on a diet.",
    'The toaster just whispered a haiku about toast.',
    'My brain is currently on vacation in Narnia.',
    'The old lighthouse stood sentinel against the raging sea, its beam piercing through the stormy night',
    'A curious cat batted at a dust bunny under the couch, contemplating its next move',
    'The aroma of freshly baked bread filled the air, a comforting scent on a chilly morning',
    'He whistled a jaunty tune as he walked, oblivious to the surprised glances he received',
    'Suddenly, the merry-go-round stopped and all the horses came to life',
    'She whispered a secret to the wind, hoping it would carry her words to the right ears',
    'The ancient oak tree seemed to sigh as the autumn leaves drifted to the ground',
    'A lone cyclist pedaled furiously uphill, determined to reach the summit',
    'Many of these sentences involve elements of mystery and discovery, such as abandoned places and hidden objects',
    'The scent of pine needles and damp earth clung to the forest air',
    'He carefully stacked the books, creating a precarious tower that defied gravity',
    'The first drop of rain created a perfect circle in the puddle, then another, and another',
    'Other sentences focus on sensory details and everyday observations',
    'A forgotten umbrella leaned against the wall, patiently waiting for the next downpour',
    'The sound of distant thunder rumbled, hinting at an approaching storm',
    "She found a mysterious key in the attic that didn't seem to fit any lock in the house",
    'The artist meticulously blended colors on his palette, creating a vibrant masterpiece',
    'The rhythm of the ocean waves crashing against the shore was a soothing lullaby',
    'Some sentences describe old buildings and historical elements',
    'He carefully arranged the pieces on the chessboard, planning his strategy with precision',
    'The warm glow of the fireplace cast dancing shadows across the living room walls',
    'A mischievous squirrel chattered from the branch, daring the dog to chase him',
    'She hummed a wordless melody as she walked through the blossoming garden',
    'The taste of homemade apple pie brought back a flood of childhood memories',
    'Themes of adventure and unexplained occurrences are also present',
    'The creaking stairs seemed to protest with every step, adding to the eerie atmosphere',
    "A single feather drifted down, a gentle reminder of a bird's flight",
    'Some sentences feature mysterious locations and strange phenomena',
    'She watched the clouds drift by, imagining shapes and stories in their changing forms',
    'The aroma of freshly brewed coffee invigorated the sleepy morning air',
    'He carefully poured the tea, steam rising in delicate tendrils from the cup',
    'The distant sound of a train whistle pierced the quiet evening',
    'She received a series of anonymous letters that predicted future events',
    'A stray dog trotted past, its tail wagging tentatively',
    'Ancient and rumored places appear in some sentences',
    'He discovered an old photograph that showed his town as it was a hundred years ago',
    'The strange fog that rolled in one evening seemed to hide something sinister',
    'Hidden items with unusual properties are mentioned',
    'Old structures with hidden activities are described',
    'Unexplained sounds and hidden areas are included',
    'Secret historical locations are referenced',
    'Messages and inheritances with hidden meanings are present',
    'Mysterious lights are featured',
    'Discoveries of old correspondence revealing significant past events are included',
    'The scent of rain on dry pavement was surprisingly pleasant',
    'She noticed a small, forgotten wildflower pushing through the cracks in the sidewalk',
    'He smiled at the simple joy of watching the children play in the park',
    'The subtle changes in the autumn landscape were a testament to the passage of time',
    'A quiet melody hummed from the antique radio in the corner, a relic from another era',
    'The sun dipped below the horizon, painting the sky with fiery hues',
  ];

  static List<String> get allSentences => _sentences;
}
